# Generated by Django 5.1.3 on 2024-11-17 05:56

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranseConfigPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=200, verbose_name='Название свойства')),
                ('sections', django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Разрезы')),
                ('values', django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Значения')),
            ],
            options={
                'verbose_name': 'Разрез',
                'verbose_name_plural': 'Разрезы',
            },
        ),
        migrations.AlterField(
            model_name='directory',
            name='directoryItems',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Элементы справочника'),
        ),
    ]
