# Generated by Django 5.1.3 on 2024-11-17 07:44

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranseConfigPanel', '0002_sections_alter_directory_directoryitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('properties', django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Свойства')),
                ('propertiesSections', django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Свойства с разрезами')),
            ],
            options={
                'verbose_name': 'Страховой продукт',
                'verbose_name_plural': 'Страховые продукты',
            },
        ),
    ]
